name: Build & Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  staticcheck:
    name: runner / staticcheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: reviewdog/action-staticcheck@v1
        with:
          filter_mode: nofilter
        
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
        
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Unit test.
        run: make test-coverage

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [staticcheck, test]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
        
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: make build