name: Build & Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    name: runner / staticcheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: reviewdog/action-staticcheck@v1
        with:
          filter_mode: nofilter

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build
        run: go build -v ./..

      - name: Test
        run: go test -v ./..
